### ISSUE TITLE
Commands in the setup process fail if Yarn or Brunch are missing

### ISSUE THREAD

**Issue by dylnclrk** [carbonfive/razor#15]
### Issue

Running `$ razor new myCoolApp` gives output which suggests users run `yarn` and `brunch` commands to complete set-up.

```
$ razor new myCoolApp

# [...]

# Install your javascript dependencies
$ yarn install

# Build your javascript dependencies
$ brunch build

# [...]
```

But running `yarn install` or `brunch build` on a machine that doesn't have `yarn`/`brunch` installed will lead to 😢  `-bash: brunch: command not found`. 

Let's give the users some more guidance on what to do here.

### Reproduction steps

1. on a machine w/o `brunch` or `yarn` installed
2. run `razor new myCoolApp`
3. Follow set up instructions in output. Get to `yarn` or `brunch` step:

  * expect
```$ yarn install
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 74.48s.
```
  * see:
```
$ yarn install
-bash: yarn: command not found
```

**Comment by dylnclrk** [comment]
Should we:
* add a dependencies section to the introduction section? We could have a blurb about how Razor requires yarn & brunch are installed before set-up.
* Change the output of `razor new`:
```
# Build your javascript dependencies. You will need to install brunch first if you do not already have it. See https://github.com/brunch/brunch for installation instructions.
$ brunch build
```

**Comment by dylnclrk** [comment]
Happy to take this on as a first contribution to Razor.

**Comment by craiglyons** [comment]
@dylnclrk Thanks! I think adding both would be best.
- for the CLI instructions, let's keep it to one line, i.e. `Build your js dependencies. You'll need brunch installed and in your path.` or something like that, and similar for yarn. 
- for the README dependencies, let's add the installation link like you suggested.
